// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4X_gE9fejjdEU-1nlV8yFQAQt-hJWnNk',
    appId: '1:1037733346379:web:ae3daf5e32a581fe10a1ce',
    messagingSenderId: '1037733346379',
    projectId: 'mindset-374be',
    authDomain: 'mindset-374be.firebaseapp.com',
    databaseURL: 'https://mindset-374be-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mindset-374be.appspot.com',
    measurementId: 'G-SM4JKMWKQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaerEspxZmwdyl14u7wa4SXbgSIpWjt3s',
    appId: '1:1037733346379:android:f91ff2eeff41994910a1ce',
    messagingSenderId: '1037733346379',
    projectId: 'mindset-374be',
    databaseURL: 'https://mindset-374be-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mindset-374be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW4Yq1wEG4bmDs3j9KrVGAXB9DQ4JEDGI',
    appId: '1:1037733346379:ios:8f04409c21dd3a6c10a1ce',
    messagingSenderId: '1037733346379',
    projectId: 'mindset-374be',
    databaseURL: 'https://mindset-374be-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mindset-374be.appspot.com',
    iosBundleId: 'com.example.mediumCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW4Yq1wEG4bmDs3j9KrVGAXB9DQ4JEDGI',
    appId: '1:1037733346379:ios:8f04409c21dd3a6c10a1ce',
    messagingSenderId: '1037733346379',
    projectId: 'mindset-374be',
    databaseURL: 'https://mindset-374be-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mindset-374be.appspot.com',
    iosBundleId: 'com.example.mediumCloneFlutter',
  );
}
